version = 0.1

[default.deploy.parameters]
stack_name = "vault-search-proxy"
resolve_s3 = true
s3_prefix = "vault-search-proxy"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "AllowedOrigin=\"*\" AllowAnyHost=\"0\" RequestTimeoutMs=\"10000\" LogRetentionDays=\"30\" ThrottlingRateLimit=\"10\" ThrottlingBurstLimit=\"25\" LambdaReservedConcurrency=\"-1\""
image_repositories = []

[default.global.parameters]
region = "us-west-1"
